//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.Device {

    public enum GetApiDeviceDeviceSerialandobjectId {

        public static let service = APIService<Response>(id: "getApiDeviceDeviceSerial}&objectId}", tag: "Device", method: "GET", path: "/api/Device/deviceSerial={deviceSerial}&objectId={objectId}", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var deviceSerial: String

                public var objectId: Int

                public init(deviceSerial: String, objectId: Int) {
                    self.deviceSerial = deviceSerial
                    self.objectId = objectId
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetApiDeviceDeviceSerialandobjectId.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(deviceSerial: String, objectId: Int) {
                let options = Options(deviceSerial: deviceSerial, objectId: objectId)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{deviceSerial}", with: "\(self.options.deviceSerial)").replacingOccurrences(of: "{objectId}", with: "\(self.options.objectId)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = ObjectValueModel

            /** Success */
            case status200(ObjectValueModel)

            public var success: ObjectValueModel? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(ObjectValueModel.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
