//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.Device {

    public enum GetApiDeviceDeviceIdandobjectIdandstartDateandendDate {

        public static let service = APIService<Response>(id: "getApiDeviceDeviceId}&objectId}&startDate}&endDate}", tag: "Device", method: "GET", path: "/api/Device/deviceId}&objectId}&startDate}&endDate}", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var deviceId: String

                public var objectId: Int

                public var startDate: String

                public var endDate: String

                public init(deviceId: String, objectId: Int, startDate: String, endDate: String) {
                    self.deviceId = deviceId
                    self.objectId = objectId
                    self.startDate = startDate
                    self.endDate = endDate
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetApiDeviceDeviceIdandobjectIdandstartDateandendDate.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(deviceId: String, objectId: Int, startDate: String, endDate: String) {
                let options = Options(deviceId: deviceId, objectId: objectId, startDate: startDate, endDate: endDate)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "deviceId" + "}", with: "\(self.options.deviceId)").replacingOccurrences(of: "{" + "objectId" + "}", with: "\(self.options.objectId)").replacingOccurrences(of: "{" + "startDate" + "}", with: "\(self.options.startDate)").replacingOccurrences(of: "{" + "endDate" + "}", with: "\(self.options.endDate)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = [ObjectValueModel]

            /** Success */
            case status200([ObjectValueModel])

            public var success: [ObjectValueModel]? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode([ObjectValueModel].self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
